In [20]:
import torch 

In [21]:
x = torch.Tensor(5,3)   #tensor can be seen as a numpy array or a multidimensional array
x

tensor(1.00000e-33 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 8.3926,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 8.4268,  0.0000,  0.0000]])

In [22]:
x = torch.rand(5,3) # during [0,1],uniform initialization the tensor
print(x.size())

torch.Size([5, 3])


In [23]:
x.size()[1],x.size()[0] # view the row and column about the tensor

(3, 5)

In [24]:
# addition ways
y = torch.Tensor(5,3)
result = torch.Tensor(5,3)
torch.add(x,y,out = result)
x+y,torch.add(x,y),result,x.add(y)

(tensor([[ 0.4374,  0.1779,  0.2830],
         [ 0.0504,  0.5062,  0.2361],
         [ 0.5039,  0.5979,  0.3655],
         [ 0.4720,  0.4378,  0.4479],
         [ 0.1218,  0.0749,  0.1958]]), tensor([[ 0.4374,  0.1779,  0.2830],
         [ 0.0504,  0.5062,  0.2361],
         [ 0.5039,  0.5979,  0.3655],
         [ 0.4720,  0.4378,  0.4479],
         [ 0.1218,  0.0749,  0.1958]]), tensor([[ 0.4374,  0.1779,  0.2830],
         [ 0.0504,  0.5062,  0.2361],
         [ 0.5039,  0.5979,  0.3655],
         [ 0.4720,  0.4378,  0.4479],
         [ 0.1218,  0.0749,  0.1958]]), tensor([[ 0.4374,  0.1779,  0.2830],
         [ 0.0504,  0.5062,  0.2361],
         [ 0.5039,  0.5979,  0.3655],
         [ 0.4720,  0.4378,  0.4479],
         [ 0.1218,  0.0749,  0.1958]]))

In [25]:
x.add_(y) #this will change the x

tensor([[ 0.4374,  0.1779,  0.2830],
        [ 0.0504,  0.5062,  0.2361],
        [ 0.5039,  0.5979,  0.3655],
        [ 0.4720,  0.4378,  0.4479],
        [ 0.1218,  0.0749,  0.1958]])

In [26]:
z = x.numpy()  # tensor->numpy
print(z)

[[0.43739486 0.17794251 0.28295857]
 [0.05037767 0.5062108  0.23614001]
 [0.50391096 0.59793115 0.36553937]
 [0.47195226 0.43781447 0.44789994]
 [0.12182218 0.07490569 0.19577616]]


In [27]:
z=torch.from_numpy(z) # numpy->tensor
print(z)
# please remember the tensor and numpy share the memory space.

tensor([[ 0.4374,  0.1779,  0.2830],
        [ 0.0504,  0.5062,  0.2361],
        [ 0.5039,  0.5979,  0.3655],
        [ 0.4720,  0.4378,  0.4479],
        [ 0.1218,  0.0749,  0.1958]])


In [29]:
#Autograd.
from torch.autograd import Variable

In [46]:
x = torch.ones(2,2)
x = Variable(x,requires_grad=True)  # tensor->variable
y = x.sum()
y.backward()  #back-propagation
x.grad # Calculate the grad

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [47]:
y.backward()
print(x.grad)
x.grad.data.zero_()  #clear the grad zero
print(x.grad)
y.grad_fn

tensor([[ 2.,  2.],
        [ 2.,  2.]])
tensor([[ 0.,  0.],
        [ 0.,  0.]])


In [ ]:
x = x.data  # variable->tensor

In [3]:
#neural network nn
import torch.nn as nn  
import torch.nn.functional as F

In [3]:
import torch.nn as nn
import torch.nn.functional as F
class Net(nn.Module):  #create a class which is nn.Module's derived class
    def __init__(self):  # constructor
        super(Net,self).__init__()  # father class's constructor
        self.conv1 = nn.Conv2d(1, 6, 5) #first convolution layer
        self.conv2 = nn.Conv2d(6, 16, 5) #second convolution layer
        self.fc1 = nn.Linear(16*5*5, 120) #full connection  layer
        self.fc2 = nn.Linear(120, 84) #full connection  layer        
        self.fc3 = nn.Linear(84, 10) #full connection  layer
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))  # convolution ->  activate -> pooling
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)  # convolution ->  activate -> pooling
        x = x.view(x.size()[0], -1) #reshape the size
        x = F.relu(self.fc1(x))  #  active fuction + linear layer
        x = F.relu(self.fc2(x)) # active fuction + linear layer
        x = self.fc3(x)  # output
        return x
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
